### ISSUE TITLE
Incorrect Docker Compose Generation

### ISSUE THREAD

**Issue by currenjin** [currenjin/wharf#8]
# Incorrect Docker Compose Generation

## Current Behavior
Currently, the generated docker-compose.yml has an incorrect service configuration:

```yaml
version: '3.8'
services:
 app:
   image: openjdk:17-jdk-slim    # This is incorrect
   ports:
     - 8080:8080
   environment:
     - SPRING_PROFILES_ACTIVE=dev
```

## Expected Behavior
The docker-compose.yml should use build instead of image to build from Dockerfile:
```yaml
version: '3.8'
services:
  app:
    build: .                      # This is correct
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev
```
